export const transactions = [
  {
    id: 'Qiu6CeNctLShkSfyRELkgivc3bfHffGmiCQZHMj3JU1nM4c3f',
    chainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
    type: 'export',
    inputs: [
      {
        output: {
          id: '2EYX8qZAViicr7s4WoYM69uFxY61dKZHxt1guuU752iz6w6FCd',
          transactionID: '4xmEgm1UzQ3UYmJLkRNzxkpBWeevYXYdFYx9aM8bq6Go8TGDM',
          outputIndex: 0,
          assetID: 'o8seyjX6WupqJ1CE8CeaozK13kqVgc4DFvdvc4crfacLFBauW',
          stake: false,
          frozen: false,
          stakeableout: false,
          genesisutxo: false,
          outputType: 7,
          amount: '9998298250',
          locktime: 0,
          stakeLocktime: 0,
          threshold: 1,
          addresses: ['columbus1y0zajcf8qce2aw0p3ksh5umnjel7cad860m88g'],
          caddresses: null,
          timestamp: '2022-07-04T13:09:23Z',
          redeemingTransactionID:
            'Qiu6CeNctLShkSfyRELkgivc3bfHffGmiCQZHMj3JU1nM4c3f',
          chainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
          inChainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
          outChainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
          groupID: 0,
          payload: '',
          block: '',
          nonce: 0,
          rewardUtxo: false,
        },
        credentials: [
          {
            address: 'columbus1y0zajcf8qce2aw0p3ksh5umnjel7cad860m88g',
            public_key: 'A4YbFCoTU0qYlJV23FN+viB4rLYCE/qO5pJfC5ih1wGF',
            signature:
              'EB4F9fCwchIBcBDgxcKo1awMUbkPPA9tQhBA8ot4TqwYuAUhbWeoA3vEHJ0///+seLPFAvG+wbh9JTGUYsJ+GAA=',
          },
        ],
      },
    ],
    outputs: [
      {
        id: '5xcMFbYPGwjEeVQu9SAL6vUrA9c9qvBd2mnDbjJHSTQ9gSi8B',
        transactionID: 'Qiu6CeNctLShkSfyRELkgivc3bfHffGmiCQZHMj3JU1nM4c3f',
        outputIndex: 1,
        assetID: 'o8seyjX6WupqJ1CE8CeaozK13kqVgc4DFvdvc4crfacLFBauW',
        stake: false,
        frozen: false,
        stakeableout: false,
        genesisutxo: false,
        outputType: 7,
        amount: '1000701750',
        locktime: 0,
        stakeLocktime: 0,
        threshold: 1,
        addresses: ['columbus1y0zajcf8qce2aw0p3ksh5umnjel7cad860m88g'],
        caddresses: null,
        timestamp: '2022-07-05T06:58:00Z',
        redeemingTransactionID:
          'y4t7xfqQkss2dRChsisBS2RvHzxwLcgEWXDn5bg1hGFojSJue',
        chainID: 'G52TJLLbDSxYXsijNMpKFB6kAyDVRd9DGWVWYBh86Z8sEXm1i',
        inChainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
        outChainID: 'G52TJLLbDSxYXsijNMpKFB6kAyDVRd9DGWVWYBh86Z8sEXm1i',
        groupID: 0,
        payload: '',
        block: '',
        nonce: 0,
        rewardUtxo: false,
      },
      {
        id: '4aC57x5pv2t6H564NYZfjafaRf7iBFUuQtj7KiEfEWTKQcWYv',
        transactionID: 'Qiu6CeNctLShkSfyRELkgivc3bfHffGmiCQZHMj3JU1nM4c3f',
        outputIndex: 0,
        assetID: 'o8seyjX6WupqJ1CE8CeaozK13kqVgc4DFvdvc4crfacLFBauW',
        stake: false,
        frozen: false,
        stakeableout: false,
        genesisutxo: false,
        outputType: 7,
        amount: '8996596500',
        locktime: 0,
        stakeLocktime: 0,
        threshold: 1,
        addresses: ['columbus1y0zajcf8qce2aw0p3ksh5umnjel7cad860m88g'],
        caddresses: null,
        timestamp: '2022-07-05T06:58:00Z',
        redeemingTransactionID: '',
        chainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
        inChainID: '',
        outChainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
        groupID: 0,
        payload: '',
        block: '',
        nonce: 0,
        rewardUtxo: false,
      },
    ],
    memo: '',
    inputTotals: {
      o8seyjX6WupqJ1CE8CeaozK13kqVgc4DFvdvc4crfacLFBauW: '9998298250',
    },
    outputTotals: {
      o8seyjX6WupqJ1CE8CeaozK13kqVgc4DFvdvc4crfacLFBauW: '9997298250',
    },
    reusedAddressTotals: null,
    timestamp: '2022-07-05T06:58:00Z',
    txFee: 1000000,
    genesis: false,
    rewarded: false,
    rewardedTime: null,
    epoch: 0,
    vertexId: 'M8nkwQXXXVJVc1nCR7AdMiCrHUcjMrc4Mb8tvGn7rQrewbSUe',
    validatorNodeID: '',
    validatorStart: 0,
    validatorEnd: 0,
    txBlockId: '',
  },
  {
    id: '4xmEgm1UzQ3UYmJLkRNzxkpBWeevYXYdFYx9aM8bq6Go8TGDM',
    chainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
    type: 'export',
    inputs: [
      {
        output: {
          id: '4ENkC8ZsT3C5nJ6we327PWQz3ouukMUHX5DwhJcx8jDNtHhfa',
          transactionID: '2St7fFZzJdk2BvXSVpVAW9ngHCgidy59YFTk8JBqH6moh4cUiD',
          outputIndex: 0,
          assetID: 'o8seyjX6WupqJ1CE8CeaozK13kqVgc4DFvdvc4crfacLFBauW',
          stake: false,
          frozen: false,
          stakeableout: false,
          genesisutxo: false,
          outputType: 7,
          amount: '20000000000',
          locktime: 0,
          stakeLocktime: 0,
          threshold: 1,
          addresses: ['columbus1y0zajcf8qce2aw0p3ksh5umnjel7cad860m88g'],
          caddresses: null,
          timestamp: '2022-07-04T13:09:12Z',
          redeemingTransactionID:
            '4xmEgm1UzQ3UYmJLkRNzxkpBWeevYXYdFYx9aM8bq6Go8TGDM',
          chainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
          inChainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
          outChainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
          groupID: 0,
          payload: '',
          block: '',
          nonce: 0,
          rewardUtxo: false,
        },
        credentials: [
          {
            address: 'columbus1y0zajcf8qce2aw0p3ksh5umnjel7cad860m88g',
            public_key: 'A4YbFCoTU0qYlJV23FN+viB4rLYCE/qO5pJfC5ih1wGF',
            signature:
              'lUPW/rCF//0J42oMQpoGuISvaCzVNYCC9CVX4Br4rypg0Ewm230TK4bRxZGwUJM8JVolSxJyAKu7UIwS6X+FBQA=',
          },
        ],
      },
    ],
    outputs: [
      {
        id: '2EYX8qZAViicr7s4WoYM69uFxY61dKZHxt1guuU752iz6w6FCd',
        transactionID: '4xmEgm1UzQ3UYmJLkRNzxkpBWeevYXYdFYx9aM8bq6Go8TGDM',
        outputIndex: 0,
        assetID: 'o8seyjX6WupqJ1CE8CeaozK13kqVgc4DFvdvc4crfacLFBauW',
        stake: false,
        frozen: false,
        stakeableout: false,
        genesisutxo: false,
        outputType: 7,
        amount: '9998298250',
        locktime: 0,
        stakeLocktime: 0,
        threshold: 1,
        addresses: ['columbus1y0zajcf8qce2aw0p3ksh5umnjel7cad860m88g'],
        caddresses: null,
        timestamp: '2022-07-04T13:09:23Z',
        redeemingTransactionID:
          'Qiu6CeNctLShkSfyRELkgivc3bfHffGmiCQZHMj3JU1nM4c3f',
        chainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
        inChainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
        outChainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
        groupID: 0,
        payload: '',
        block: '',
        nonce: 0,
        rewardUtxo: false,
      },
      {
        id: '2Nx99d8d3AW1YgjaRwN9KUBkUQQxn6L1hqVw1CRFpe6zShvrfy',
        transactionID: '4xmEgm1UzQ3UYmJLkRNzxkpBWeevYXYdFYx9aM8bq6Go8TGDM',
        outputIndex: 1,
        assetID: 'o8seyjX6WupqJ1CE8CeaozK13kqVgc4DFvdvc4crfacLFBauW',
        stake: false,
        frozen: false,
        stakeableout: false,
        genesisutxo: false,
        outputType: 7,
        amount: '10000701750',
        locktime: 0,
        stakeLocktime: 0,
        threshold: 1,
        addresses: ['columbus1y0zajcf8qce2aw0p3ksh5umnjel7cad860m88g'],
        caddresses: null,
        timestamp: '2022-07-04T13:09:23Z',
        redeemingTransactionID:
          'GhxuDK1LUa3yAitEwfr7SNV6ekMFDBPd43T6Fp49HMdZhcDYi',
        chainID: 'G52TJLLbDSxYXsijNMpKFB6kAyDVRd9DGWVWYBh86Z8sEXm1i',
        inChainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
        outChainID: 'G52TJLLbDSxYXsijNMpKFB6kAyDVRd9DGWVWYBh86Z8sEXm1i',
        groupID: 0,
        payload: '',
        block: '',
        nonce: 0,
        rewardUtxo: false,
      },
    ],
    memo: '',
    inputTotals: {
      o8seyjX6WupqJ1CE8CeaozK13kqVgc4DFvdvc4crfacLFBauW: '20000000000',
    },
    outputTotals: {
      o8seyjX6WupqJ1CE8CeaozK13kqVgc4DFvdvc4crfacLFBauW: '19999000000',
    },
    reusedAddressTotals: null,
    timestamp: '2022-07-04T13:09:23Z',
    txFee: 1000000,
    genesis: false,
    rewarded: false,
    rewardedTime: null,
    epoch: 0,
    vertexId: '2rgmm6KgDa4gz1YkaDvn76sixLxQyNWtDDYdYDa4Hny9GdsyRK',
    validatorNodeID: '',
    validatorStart: 0,
    validatorEnd: 0,
    txBlockId: '',
  },
  {
    id: '2St7fFZzJdk2BvXSVpVAW9ngHCgidy59YFTk8JBqH6moh4cUiD',
    chainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
    type: 'base',
    inputs: [
      {
        output: {
          id: '2r11tN1hwTrnmTCz6LFrCAVW8BjqTeKc89KEGFxeX36JHFrr2H',
          transactionID: '2SouGT13eAQRPjDS6vNEph9FA6nV66QaPSrMDZtRP4LQj1jGCE',
          outputIndex: 1,
          assetID: 'o8seyjX6WupqJ1CE8CeaozK13kqVgc4DFvdvc4crfacLFBauW',
          stake: false,
          frozen: false,
          stakeableout: false,
          genesisutxo: false,
          outputType: 7,
          amount: '986323974000000',
          locktime: 0,
          stakeLocktime: 0,
          threshold: 1,
          addresses: ['columbus1zawetvfggky6yvx5wdcn0tjsalw9ql9dz537x7'],
          caddresses: null,
          timestamp: '2022-07-04T06:50:14Z',
          redeemingTransactionID:
            '2St7fFZzJdk2BvXSVpVAW9ngHCgidy59YFTk8JBqH6moh4cUiD',
          chainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
          inChainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
          outChainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
          groupID: 0,
          payload: '',
          block: '',
          nonce: 0,
          rewardUtxo: false,
        },
        credentials: [
          {
            address: 'columbus1zawetvfggky6yvx5wdcn0tjsalw9ql9dz537x7',
            public_key: 'AmSGBLZe0jjbbH2ouSC91wnP56KDBUcBQMescyzZCJ3h',
            signature:
              'BJxX8bsdrgWsmnt4LvkA6+otrVhaulNhgyf51oIWaLZl8QXusVIAtjZkFqqE079ycxcheVYzAkugSL1no5iB8QA=',
          },
        ],
      },
    ],
    outputs: [
      {
        id: '4ENkC8ZsT3C5nJ6we327PWQz3ouukMUHX5DwhJcx8jDNtHhfa',
        transactionID: '2St7fFZzJdk2BvXSVpVAW9ngHCgidy59YFTk8JBqH6moh4cUiD',
        outputIndex: 0,
        assetID: 'o8seyjX6WupqJ1CE8CeaozK13kqVgc4DFvdvc4crfacLFBauW',
        stake: false,
        frozen: false,
        stakeableout: false,
        genesisutxo: false,
        outputType: 7,
        amount: '20000000000',
        locktime: 0,
        stakeLocktime: 0,
        threshold: 1,
        addresses: ['columbus1y0zajcf8qce2aw0p3ksh5umnjel7cad860m88g'],
        caddresses: null,
        timestamp: '2022-07-04T13:09:12Z',
        redeemingTransactionID:
          '4xmEgm1UzQ3UYmJLkRNzxkpBWeevYXYdFYx9aM8bq6Go8TGDM',
        chainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
        inChainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
        outChainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
        groupID: 0,
        payload: '',
        block: '',
        nonce: 0,
        rewardUtxo: false,
      },
      {
        id: 'bUJnpLbAzmtQuUfDdDzt7idrPDn9J53CozLmAMEL9HbXHzhqZ',
        transactionID: '2St7fFZzJdk2BvXSVpVAW9ngHCgidy59YFTk8JBqH6moh4cUiD',
        outputIndex: 1,
        assetID: 'o8seyjX6WupqJ1CE8CeaozK13kqVgc4DFvdvc4crfacLFBauW',
        stake: false,
        frozen: false,
        stakeableout: false,
        genesisutxo: false,
        outputType: 7,
        amount: '986303973000000',
        locktime: 0,
        stakeLocktime: 0,
        threshold: 1,
        addresses: ['columbus1zawetvfggky6yvx5wdcn0tjsalw9ql9dz537x7'],
        caddresses: null,
        timestamp: '2022-07-04T13:09:12Z',
        redeemingTransactionID: '',
        chainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
        inChainID: '',
        outChainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
        groupID: 0,
        payload: '',
        block: '',
        nonce: 0,
        rewardUtxo: false,
      },
    ],
    memo: 'RGlzY29yZCBmYXVjZXQgVUlEOiAyMDUwMjI4MzMzNjgyMzYwMzI=',
    inputTotals: {
      o8seyjX6WupqJ1CE8CeaozK13kqVgc4DFvdvc4crfacLFBauW: '986323974000000',
    },
    outputTotals: {
      o8seyjX6WupqJ1CE8CeaozK13kqVgc4DFvdvc4crfacLFBauW: '986323973000000',
    },
    reusedAddressTotals: null,
    timestamp: '2022-07-04T13:09:12Z',
    txFee: 1000000,
    genesis: false,
    rewarded: false,
    rewardedTime: null,
    epoch: 0,
    vertexId: '2TvVKcQBjsQTFp2hb9yvptVZeDRMckQXCr15MxwpzAnsyhPqsa',
    validatorNodeID: '',
    validatorStart: 0,
    validatorEnd: 0,
    txBlockId: '',
  },
  {
    id: '2St7fFZzJdk2BvXSVpVAW9ngHCgidy59YFTk8JBqH6moh4cUiD',
    chainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
    type: 'base',
    inputs: [
      {
        output: {
          id: '2r11tN1hwTrnmTCz6LFrCAVW8BjqTeKc89KEGFxeX36JHFrr2H',
          transactionID: '2SouGT13eAQRPjDS6vNEph9FA6nV66QaPSrMDZtRP4LQj1jGCE',
          outputIndex: 1,
          assetID: 'o8seyjX6WupqJ1CE8CeaozK13kqVgc4DFvdvc4crfacLFBauW',
          stake: false,
          frozen: false,
          stakeableout: false,
          genesisutxo: false,
          outputType: 7,
          amount: '986323974000000',
          locktime: 0,
          stakeLocktime: 0,
          threshold: 1,
          addresses: ['columbus1zawetvfggky6yvx5wdcn0tjsalw9ql9dz537x7'],
          caddresses: null,
          timestamp: '2022-07-04T06:50:14Z',
          redeemingTransactionID:
            '2St7fFZzJdk2BvXSVpVAW9ngHCgidy59YFTk8JBqH6moh4cUiD',
          chainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
          inChainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
          outChainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
          groupID: 0,
          payload: '',
          block: '',
          nonce: 0,
          rewardUtxo: false,
        },
        credentials: [
          {
            address: 'columbus1zawetvfggky6yvx5wdcn0tjsalw9ql9dz537x7',
            public_key: 'AmSGBLZe0jjbbH2ouSC91wnP56KDBUcBQMescyzZCJ3h',
            signature:
              'BJxX8bsdrgWsmnt4LvkA6+otrVhaulNhgyf51oIWaLZl8QXusVIAtjZkFqqE079ycxcheVYzAkugSL1no5iB8QA=',
          },
        ],
      },
    ],
    outputs: [
      {
        id: '4ENkC8ZsT3C5nJ6we327PWQz3ouukMUHX5DwhJcx8jDNtHhfa',
        transactionID: '2St7fFZzJdk2BvXSVpVAW9ngHCgidy59YFTk8JBqH6moh4cUiD',
        outputIndex: 0,
        assetID: 'o8seyjX6WupqJ1CE8CeaozK13kqVgc4DFvdvc4crfacLFBauW',
        stake: false,
        frozen: false,
        stakeableout: false,
        genesisutxo: false,
        outputType: 7,
        amount: '20000000000',
        locktime: 0,
        stakeLocktime: 0,
        threshold: 1,
        addresses: ['columbus1y0zajcf8qce2aw0p3ksh5umnjel7cad860m88g'],
        caddresses: null,
        timestamp: '2022-07-04T13:09:12Z',
        redeemingTransactionID:
          '4xmEgm1UzQ3UYmJLkRNzxkpBWeevYXYdFYx9aM8bq6Go8TGDM',
        chainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
        inChainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
        outChainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
        groupID: 0,
        payload: '',
        block: '',
        nonce: 0,
        rewardUtxo: false,
      },
      {
        id: 'bUJnpLbAzmtQuUfDdDzt7idrPDn9J53CozLmAMEL9HbXHzhqZ',
        transactionID: '2St7fFZzJdk2BvXSVpVAW9ngHCgidy59YFTk8JBqH6moh4cUiD',
        outputIndex: 1,
        assetID: 'o8seyjX6WupqJ1CE8CeaozK13kqVgc4DFvdvc4crfacLFBauW',
        stake: false,
        frozen: false,
        stakeableout: false,
        genesisutxo: false,
        outputType: 7,
        amount: '986303973000000',
        locktime: 0,
        stakeLocktime: 0,
        threshold: 1,
        addresses: ['columbus1zawetvfggky6yvx5wdcn0tjsalw9ql9dz537x7'],
        caddresses: null,
        timestamp: '2022-07-04T13:09:12Z',
        redeemingTransactionID: '',
        chainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
        inChainID: '',
        outChainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
        groupID: 0,
        payload: '',
        block: '',
        nonce: 0,
        rewardUtxo: false,
      },
    ],
    memo: 'RGlzY29yZCBmYXVjZXQgVUlEOiAyMDUwMjI4MzMzNjgyMzYwMzI=',
    inputTotals: {
      o8seyjX6WupqJ1CE8CeaozK13kqVgc4DFvdvc4crfacLFBauW: '986323974000000',
    },
    outputTotals: {
      o8seyjX6WupqJ1CE8CeaozK13kqVgc4DFvdvc4crfacLFBauW: '986323973000000',
    },
    reusedAddressTotals: null,
    timestamp: '2022-07-04T13:09:12Z',
    txFee: 1000000,
    genesis: false,
    rewarded: false,
    rewardedTime: null,
    epoch: 0,
    vertexId: '2TvVKcQBjsQTFp2hb9yvptVZeDRMckQXCr15MxwpzAnsyhPqsa',
    validatorNodeID: '',
    validatorStart: 0,
    validatorEnd: 0,
    txBlockId: '',
  },
  {
    id: '2St7fFZzJdk2BvXSVpVAW9ngHCgidy59YFTk8JBqH6moh4cUiD',
    chainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
    type: 'base',
    inputs: [
      {
        output: {
          id: '2r11tN1hwTrnmTCz6LFrCAVW8BjqTeKc89KEGFxeX36JHFrr2H',
          transactionID: '2SouGT13eAQRPjDS6vNEph9FA6nV66QaPSrMDZtRP4LQj1jGCE',
          outputIndex: 1,
          assetID: 'o8seyjX6WupqJ1CE8CeaozK13kqVgc4DFvdvc4crfacLFBauW',
          stake: false,
          frozen: false,
          stakeableout: false,
          genesisutxo: false,
          outputType: 7,
          amount: '986323974000000',
          locktime: 0,
          stakeLocktime: 0,
          threshold: 1,
          addresses: ['columbus1zawetvfggky6yvx5wdcn0tjsalw9ql9dz537x7'],
          caddresses: null,
          timestamp: '2022-07-04T06:50:14Z',
          redeemingTransactionID:
            '2St7fFZzJdk2BvXSVpVAW9ngHCgidy59YFTk8JBqH6moh4cUiD',
          chainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
          inChainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
          outChainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
          groupID: 0,
          payload: '',
          block: '',
          nonce: 0,
          rewardUtxo: false,
        },
        credentials: [
          {
            address: 'columbus1zawetvfggky6yvx5wdcn0tjsalw9ql9dz537x7',
            public_key: 'AmSGBLZe0jjbbH2ouSC91wnP56KDBUcBQMescyzZCJ3h',
            signature:
              'BJxX8bsdrgWsmnt4LvkA6+otrVhaulNhgyf51oIWaLZl8QXusVIAtjZkFqqE079ycxcheVYzAkugSL1no5iB8QA=',
          },
        ],
      },
    ],
    outputs: [
      {
        id: '4ENkC8ZsT3C5nJ6we327PWQz3ouukMUHX5DwhJcx8jDNtHhfa',
        transactionID: '2St7fFZzJdk2BvXSVpVAW9ngHCgidy59YFTk8JBqH6moh4cUiD',
        outputIndex: 0,
        assetID: 'o8seyjX6WupqJ1CE8CeaozK13kqVgc4DFvdvc4crfacLFBauW',
        stake: false,
        frozen: false,
        stakeableout: false,
        genesisutxo: false,
        outputType: 7,
        amount: '20000000000',
        locktime: 0,
        stakeLocktime: 0,
        threshold: 1,
        addresses: ['columbus1y0zajcf8qce2aw0p3ksh5umnjel7cad860m88g'],
        caddresses: null,
        timestamp: '2022-07-04T13:09:12Z',
        redeemingTransactionID:
          '4xmEgm1UzQ3UYmJLkRNzxkpBWeevYXYdFYx9aM8bq6Go8TGDM',
        chainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
        inChainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
        outChainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
        groupID: 0,
        payload: '',
        block: '',
        nonce: 0,
        rewardUtxo: false,
      },
      {
        id: 'bUJnpLbAzmtQuUfDdDzt7idrPDn9J53CozLmAMEL9HbXHzhqZ',
        transactionID: '2St7fFZzJdk2BvXSVpVAW9ngHCgidy59YFTk8JBqH6moh4cUiD',
        outputIndex: 1,
        assetID: 'o8seyjX6WupqJ1CE8CeaozK13kqVgc4DFvdvc4crfacLFBauW',
        stake: false,
        frozen: false,
        stakeableout: false,
        genesisutxo: false,
        outputType: 7,
        amount: '986303973000000',
        locktime: 0,
        stakeLocktime: 0,
        threshold: 1,
        addresses: ['columbus1zawetvfggky6yvx5wdcn0tjsalw9ql9dz537x7'],
        caddresses: null,
        timestamp: '2022-07-04T13:09:12Z',
        redeemingTransactionID: '',
        chainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
        inChainID: '',
        outChainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
        groupID: 0,
        payload: '',
        block: '',
        nonce: 0,
        rewardUtxo: false,
      },
    ],
    memo: 'RGlzY29yZCBmYXVjZXQgVUlEOiAyMDUwMjI4MzMzNjgyMzYwMzI=',
    inputTotals: {
      o8seyjX6WupqJ1CE8CeaozK13kqVgc4DFvdvc4crfacLFBauW: '986323974000000',
    },
    outputTotals: {
      o8seyjX6WupqJ1CE8CeaozK13kqVgc4DFvdvc4crfacLFBauW: '986323973000000',
    },
    reusedAddressTotals: null,
    timestamp: '2022-07-04T13:09:12Z',
    txFee: 1000000,
    genesis: false,
    rewarded: false,
    rewardedTime: null,
    epoch: 0,
    vertexId: '2TvVKcQBjsQTFp2hb9yvptVZeDRMckQXCr15MxwpzAnsyhPqsa',
    validatorNodeID: '',
    validatorStart: 0,
    validatorEnd: 0,
    txBlockId: '',
  },
  {
    id: '2St7fFZzJdk2BvXSVpVAW9ngHCgidy59YFTk8JBqH6moh4cUiD',
    chainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
    type: 'base',
    inputs: [
      {
        output: {
          id: '2r11tN1hwTrnmTCz6LFrCAVW8BjqTeKc89KEGFxeX36JHFrr2H',
          transactionID: '2SouGT13eAQRPjDS6vNEph9FA6nV66QaPSrMDZtRP4LQj1jGCE',
          outputIndex: 1,
          assetID: 'o8seyjX6WupqJ1CE8CeaozK13kqVgc4DFvdvc4crfacLFBauW',
          stake: false,
          frozen: false,
          stakeableout: false,
          genesisutxo: false,
          outputType: 7,
          amount: '986323974000000',
          locktime: 0,
          stakeLocktime: 0,
          threshold: 1,
          addresses: ['columbus1zawetvfggky6yvx5wdcn0tjsalw9ql9dz537x7'],
          caddresses: null,
          timestamp: '2022-07-04T06:50:14Z',
          redeemingTransactionID:
            '2St7fFZzJdk2BvXSVpVAW9ngHCgidy59YFTk8JBqH6moh4cUiD',
          chainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
          inChainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
          outChainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
          groupID: 0,
          payload: '',
          block: '',
          nonce: 0,
          rewardUtxo: false,
        },
        credentials: [
          {
            address: 'columbus1zawetvfggky6yvx5wdcn0tjsalw9ql9dz537x7',
            public_key: 'AmSGBLZe0jjbbH2ouSC91wnP56KDBUcBQMescyzZCJ3h',
            signature:
              'BJxX8bsdrgWsmnt4LvkA6+otrVhaulNhgyf51oIWaLZl8QXusVIAtjZkFqqE079ycxcheVYzAkugSL1no5iB8QA=',
          },
        ],
      },
    ],
    outputs: [
      {
        id: '4ENkC8ZsT3C5nJ6we327PWQz3ouukMUHX5DwhJcx8jDNtHhfa',
        transactionID: '2St7fFZzJdk2BvXSVpVAW9ngHCgidy59YFTk8JBqH6moh4cUiD',
        outputIndex: 0,
        assetID: 'o8seyjX6WupqJ1CE8CeaozK13kqVgc4DFvdvc4crfacLFBauW',
        stake: false,
        frozen: false,
        stakeableout: false,
        genesisutxo: false,
        outputType: 7,
        amount: '20000000000',
        locktime: 0,
        stakeLocktime: 0,
        threshold: 1,
        addresses: ['columbus1y0zajcf8qce2aw0p3ksh5umnjel7cad860m88g'],
        caddresses: null,
        timestamp: '2022-07-04T13:09:12Z',
        redeemingTransactionID:
          '4xmEgm1UzQ3UYmJLkRNzxkpBWeevYXYdFYx9aM8bq6Go8TGDM',
        chainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
        inChainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
        outChainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
        groupID: 0,
        payload: '',
        block: '',
        nonce: 0,
        rewardUtxo: false,
      },
      {
        id: 'bUJnpLbAzmtQuUfDdDzt7idrPDn9J53CozLmAMEL9HbXHzhqZ',
        transactionID: '2St7fFZzJdk2BvXSVpVAW9ngHCgidy59YFTk8JBqH6moh4cUiD',
        outputIndex: 1,
        assetID: 'o8seyjX6WupqJ1CE8CeaozK13kqVgc4DFvdvc4crfacLFBauW',
        stake: false,
        frozen: false,
        stakeableout: false,
        genesisutxo: false,
        outputType: 7,
        amount: '986303973000000',
        locktime: 0,
        stakeLocktime: 0,
        threshold: 1,
        addresses: ['columbus1zawetvfggky6yvx5wdcn0tjsalw9ql9dz537x7'],
        caddresses: null,
        timestamp: '2022-07-04T13:09:12Z',
        redeemingTransactionID: '',
        chainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
        inChainID: '',
        outChainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
        groupID: 0,
        payload: '',
        block: '',
        nonce: 0,
        rewardUtxo: false,
      },
    ],
    memo: 'RGlzY29yZCBmYXVjZXQgVUlEOiAyMDUwMjI4MzMzNjgyMzYwMzI=',
    inputTotals: {
      o8seyjX6WupqJ1CE8CeaozK13kqVgc4DFvdvc4crfacLFBauW: '986323974000000',
    },
    outputTotals: {
      o8seyjX6WupqJ1CE8CeaozK13kqVgc4DFvdvc4crfacLFBauW: '986323973000000',
    },
    reusedAddressTotals: null,
    timestamp: '2022-07-04T13:09:12Z',
    txFee: 1000000,
    genesis: false,
    rewarded: false,
    rewardedTime: null,
    epoch: 0,
    vertexId: '2TvVKcQBjsQTFp2hb9yvptVZeDRMckQXCr15MxwpzAnsyhPqsa',
    validatorNodeID: '',
    validatorStart: 0,
    validatorEnd: 0,
    txBlockId: '',
  },
  {
    id: '2St7fFZzJdk2BvXSVpVAW9ngHCgidy59YFTk8JBqH6moh4cUiD',
    chainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
    type: 'base',
    inputs: [
      {
        output: {
          id: '2r11tN1hwTrnmTCz6LFrCAVW8BjqTeKc89KEGFxeX36JHFrr2H',
          transactionID: '2SouGT13eAQRPjDS6vNEph9FA6nV66QaPSrMDZtRP4LQj1jGCE',
          outputIndex: 1,
          assetID: 'o8seyjX6WupqJ1CE8CeaozK13kqVgc4DFvdvc4crfacLFBauW',
          stake: false,
          frozen: false,
          stakeableout: false,
          genesisutxo: false,
          outputType: 7,
          amount: '986323974000000',
          locktime: 0,
          stakeLocktime: 0,
          threshold: 1,
          addresses: ['columbus1zawetvfggky6yvx5wdcn0tjsalw9ql9dz537x7'],
          caddresses: null,
          timestamp: '2022-07-04T06:50:14Z',
          redeemingTransactionID:
            '2St7fFZzJdk2BvXSVpVAW9ngHCgidy59YFTk8JBqH6moh4cUiD',
          chainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
          inChainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
          outChainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
          groupID: 0,
          payload: '',
          block: '',
          nonce: 0,
          rewardUtxo: false,
        },
        credentials: [
          {
            address: 'columbus1zawetvfggky6yvx5wdcn0tjsalw9ql9dz537x7',
            public_key: 'AmSGBLZe0jjbbH2ouSC91wnP56KDBUcBQMescyzZCJ3h',
            signature:
              'BJxX8bsdrgWsmnt4LvkA6+otrVhaulNhgyf51oIWaLZl8QXusVIAtjZkFqqE079ycxcheVYzAkugSL1no5iB8QA=',
          },
        ],
      },
    ],
    outputs: [
      {
        id: '4ENkC8ZsT3C5nJ6we327PWQz3ouukMUHX5DwhJcx8jDNtHhfa',
        transactionID: '2St7fFZzJdk2BvXSVpVAW9ngHCgidy59YFTk8JBqH6moh4cUiD',
        outputIndex: 0,
        assetID: 'o8seyjX6WupqJ1CE8CeaozK13kqVgc4DFvdvc4crfacLFBauW',
        stake: false,
        frozen: false,
        stakeableout: false,
        genesisutxo: false,
        outputType: 7,
        amount: '20000000000',
        locktime: 0,
        stakeLocktime: 0,
        threshold: 1,
        addresses: ['columbus1y0zajcf8qce2aw0p3ksh5umnjel7cad860m88g'],
        caddresses: null,
        timestamp: '2022-07-04T13:09:12Z',
        redeemingTransactionID:
          '4xmEgm1UzQ3UYmJLkRNzxkpBWeevYXYdFYx9aM8bq6Go8TGDM',
        chainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
        inChainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
        outChainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
        groupID: 0,
        payload: '',
        block: '',
        nonce: 0,
        rewardUtxo: false,
      },
      {
        id: 'bUJnpLbAzmtQuUfDdDzt7idrPDn9J53CozLmAMEL9HbXHzhqZ',
        transactionID: '2St7fFZzJdk2BvXSVpVAW9ngHCgidy59YFTk8JBqH6moh4cUiD',
        outputIndex: 1,
        assetID: 'o8seyjX6WupqJ1CE8CeaozK13kqVgc4DFvdvc4crfacLFBauW',
        stake: false,
        frozen: false,
        stakeableout: false,
        genesisutxo: false,
        outputType: 7,
        amount: '986303973000000',
        locktime: 0,
        stakeLocktime: 0,
        threshold: 1,
        addresses: ['columbus1zawetvfggky6yvx5wdcn0tjsalw9ql9dz537x7'],
        caddresses: null,
        timestamp: '2022-07-04T13:09:12Z',
        redeemingTransactionID: '',
        chainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
        inChainID: '',
        outChainID: '28Pp3JZJBABUmFQcC9ZXPjuDS6WVX8LeQP9y3DvpCXGiNiTQFV',
        groupID: 0,
        payload: '',
        block: '',
        nonce: 0,
        rewardUtxo: false,
      },
    ],
    memo: 'RGlzY29yZCBmYXVjZXQgVUlEOiAyMDUwMjI4MzMzNjgyMzYwMzI=',
    inputTotals: {
      o8seyjX6WupqJ1CE8CeaozK13kqVgc4DFvdvc4crfacLFBauW: '986323974000000',
    },
    outputTotals: {
      o8seyjX6WupqJ1CE8CeaozK13kqVgc4DFvdvc4crfacLFBauW: '986323973000000',
    },
    reusedAddressTotals: null,
    timestamp: '2022-07-04T13:09:12Z',
    txFee: 1000000,
    genesis: false,
    rewarded: false,
    rewardedTime: null,
    epoch: 0,
    vertexId: '2TvVKcQBjsQTFp2hb9yvptVZeDRMckQXCr15MxwpzAnsyhPqsa',
    validatorNodeID: '',
    validatorStart: 0,
    validatorEnd: 0,
    txBlockId: '',
  },
];
