#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Disable concurrent to run `check-types` after ESLint in lint-staged
npx lint-staged --concurrent false

# Automatically fix code with ESLint
npx eslint --fix .

# Run TypeScript compiler
# tsc

# npx tsc --noEmit --strictNullChecks --noImplicitAny

npx eslint --fix . --color --no-quiet
